jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ENC(YTqbVMjVqfEgp7hQLXl9RwbhKyybqMoQemVs0HFB1DDWfXmRPtzJ0KXMDPBJdE46QXGLF9Jl3FhUK2meJig+X5YKKlXkDixqXg3adL/9Q0SoJElIQAZ6HuEKLs+hDmQRWQWlo/rXOo64nx7APg8NFaF4o14tToUtRsGxnCQbf4Vshm3G18KOPg==)
    username: ENC(5ufiORGiaiClXRAeGun4SjAVKNtG1qKKyv69XDTSJDE=)
    password: ENC(vX7qSexOA8YDkOJWxdJ4VYb0zLoi1NInJ4OQIhI1+q/i9sLcNTkx/Q==)
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /resources/static/
  jackson:
    serialization:
      indent_output: true

socials:
  kakao:
    api:
      host: https://kapi.kakao.com
      user: /v2/user/me

jwt:
  signature:
    key: ENC(k4twR0AkqszAoIjTfAiqCK/VORPa+rdulIE3ecEYiwtab9ATfEyZnE4GcBOkv/EByOePW0oT53Y=)