jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ENC(8FcC/aWEAlFvMdMtE+KVYsAZWZpVnCD0N4He1AttXgZMvDU7iSeiiGc6XKXtSn2VmACwx2D8KAFVh4afV9IddQ7hdFp/mwb89UkMh/aX0z0LQMVYxzV7fy8qnfONnz1/2mLznTHcL+kEVykWUwK7g5gvpdrJ02C/)
    username: ENC(5ufiORGiaiClXRAeGun4SjAVKNtG1qKKyv69XDTSJDE=)
    password: ENC(vX7qSexOA8YDkOJWxdJ4VYb0zLoi1NInJ4OQIhI1+q/i9sLcNTkx/Q==)
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /resources/static/
  jackson:
    serialization:
      indent_output: true

socials:
  kakao:
    host: https://kauth.kakao.com
    oauth_api: /oauth/authorize
    token_api: /oauth/token
    redirect_uri: http://localhost:8080/oauth/codes/kakao
    grant_type: authorization_code
    client_id: ENC(ILEZvixqcNlh7OY3PnFbVd6Uo5U4mSvnzcQV8AjKkE5UgdI2yCmxALhVFBVEOnsOkeVh97B7cOIMgdb8Vr+YSw==)
    client_secret: ENC(ORaAeOYI5hlB8gG+721btx77Uv9UGnaaUxDn6DxYtL8UbHAn9Df1ByiUUq4pI/zZJDTNenAsenv357UtrbA4Wg==)